### ISSUE TITLE
ssl_error

### ISSUE THREAD

**Issue by bootsmann** [nickbabcock/bottle-ssl#1]
it does not work with cherrypy 3.6.0

Returns in Firefox:
ssl_error_rx_record_too_long
Chrome:
ERR_SSL_PROTOCOL_ERROR

Edit:
https://bitbucket.org/cherrypy/cherrypy/issue/1293/ssl-broken-under-pypy-221

**Comment by nickbabcock** [comment]
My apologies for the non-response! I also came across the same problem and so I had to use an older version that I knew worked. Check out [requirements.txt](https://github.com/nickbabcock/bottle-ssl/blob/master/requirements.txt) for the versions that do jive together.
