### ISSUE TITLE
TypeError when trying to run

### ISSUE THREAD

**Issue by ghost** [nickbabcock/bottle-ssl#2]
I installed all dependencies but I get this error when I'm trying to run main.py
`Traceback (most recent call last):
  File "C:/Users/kig0pkt12/PycharmProjects/dreadnought/main.py", line 5, in <module>
    from cheroot.ssl.pyopenssl import pyOpenSSLAdapter
  File "C:\WP36\python-3.6.2rc2.amd64\lib\site-packages\cheroot\ssl\pyopenssl.py", line 49, in <module>
    class SSL_fileobject(MakeFile):
TypeError: function() argument 1 must be code, not str`

**Comment by nickbabcock** [comment]
Hey xeno, looks like cheroot doesn't run on python3: https://github.com/cherrypy/cheroot/issues/6

This is disappointing to say the least. I'll have to see if I can replace cherrypy / cheroot with something else. Thank you for the report!

**Comment by nickbabcock** [comment]
Added python3 compatibility in 3c6df563e3b63e8d by removing pyopenssl dependency.
