### ISSUE TITLE
name 'certfile' is not defined

### ISSUE THREAD

**Issue by mrdc** [nickbabcock/bottle-ssl#63]
Hello,

Unfortunately, I receive `name 'certfile' is not defined` when I try to run my script.

```
  certfile: "~/HTTPS/192.168.1.1.pem",
NameError: name 'certfile' is not defined
```

**my_script.py:**
```
.....
options = {
  certfile: "~/HTTPS/192.168.1.1.pem",
  keyfile: "~/HTTPS/device.pem"
}

run(host='0.0.0.0', port=8900,server='cheroot', debug=False, options=options)
```

**Comment by mrdc** [comment]
So, there is an error in https://github.com/nickbabcock/bottle-ssl/blob/master/README.md
Correct code (single quotes for certfile and keyfile):
```
options = {
  'certfile': 'cert.pem',
  'keyfile': 'keyfile.pem'
}
```

**Comment by nickbabcock** [comment]
Thank you for pointing it out, it has now been fixed.
